In [1]:
import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.svm import LinearSVC, SVC, LinearSVR, SVR

# Linear SVM Classification

In [5]:
#Defining classification conditions for the Linear SVC
iris = datasets.load_iris()

X = iris.data[:, (2,3)] #Taking petal length and petal width as feature values
y = (iris.target == 2).astype(np.int64) #Checking for Iris-Virginica

In [6]:
#Creating a pipeline for SVM linear classifier
svm_classifier = Pipeline((
    ("scaler", StandardScaler()),
    ("linear_svc", LinearSVC(C=1, loss="hinge"))
))

In [7]:
#Training the svm_classifier and predicting results from it
svm_classifier.fit(X, y)
svm_classifier.predict([[5.5, 1.7]])

array([1])

# Non-Linear SVM Classification

### Using Linear SVM Classifier with Polynomial Features

In [8]:
#Creating polynomial SVM classifier using 3rd degree polynomial features
poly_svm_classifier = Pipeline((
    ("poly_features", PolynomialFeatures(degree=3, include_bias=False)),
    ("scaler", StandardScaler()),
    ("linear_svc", LinearSVC(C=10, loss="hinge"))
))

In [9]:
#Training the polynomial svm_classifier and predicting results from it
poly_svm_classifier.fit(X, y)
poly_svm_classifier.predict([[5.5, 1.7]])

array([1])

### Using SVM Classifier with Polynomial Kernel

In [12]:
#Creating polynomial SVM classifier using polynomial kernel
poly_kernel_svm_classifier = Pipeline((
    ("scaler", StandardScaler()),
    ("svm_classifer", SVC(kernel="poly", degree=3, coef0=1, C=5))
))

In [13]:
#Training the polynomial svm_classifier and predicting results from it
poly_kernel_svm_classifier.fit(X, y)
poly_kernel_svm_classifier.predict([[5.5, 1.7]]) 

array([1])

### Using Similarity Function (Gaussian RBF Kernel)

In [19]:
#Creating polynomial SVM classifier using Gaussian RBF Kernel
rbf_kernel_svm_classifier = Pipeline((
    ("scaler", StandardScaler()),
    ("svm_classifer", SVC(kernel="rbf", gamma=5, C=1))
))

In [20]:
#Training the polynomial rbf svm_classifier and predicting results from it
rbf_kernel_svm_classifier.fit(X, y)
rbf_kernel_svm_classifier.predict([[5.5, 1.7]])

array([1])

# Linear SVM Regression

In [32]:
#Creating a pipeline for SVM Regressor
svm_regressor = Pipeline((
    ("scaler", StandardScaler()),
    ("linear_svc", LinearSVR(epsilon=0.1))
))

In [33]:
#Training the Linear SVM Regressor and predicting results from it
svm_regressor.fit(X,y)
svm_regressor.predict([[5.5, 1.7]])

array([0.60559563])

# Non-Linear SVM Regression

In [28]:
#Creating a pipeline for Polynomial SVM Regressor
poly_svm_regressor = Pipeline((
    ("scaler", StandardScaler()),
    ("svr", SVR(kernel="poly", degree=2, C=100, epsilon=0.1))
))

In [29]:
#Training the Polynomial SVM Regressor and predicting results from it
poly_svm_regressor.fit(X, y)
poly_svm_regressor.predict([[5.5, 1.7]])

array([0.17935854])